"""FastAPI control plane: catalog, submissions and progress.

Run locally:  uvicorn api.main:app --reload
"""
import asyncio
import json
import re
from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.concurrency import run_in_threadpool
from fastapi.middleware.cors import CORSMiddleware

from grader.run import grade

from . import schemas
from .catalog import Catalog
from .config import Settings
from .db import Database

USER_ID_RE = re.compile(r"^[A-Za-z0-9_-]{8,64}$")


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or Settings()

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        app.state.catalog = Catalog(settings.exercises_dir)
        app.state.db = Database(settings.database_path)
        app.state.run_slots = asyncio.Semaphore(settings.max_concurrent_runs)
        app.state.running_users = set()
        yield

    app = FastAPI(title="Gradient: ML Practice Platform API", version="0.2.0", lifespan=lifespan)
    app.add_middleware(
        CORSMiddleware, allow_origins=settings.cors_origins, allow_methods=["*"], allow_headers=["*"],
    )

    # ------------------------------------------------------------- deps

    def user_id(x_user_id: str = Header(...)) -> str:
        # Anonymous learner identity generated by the client. Swap for real auth (JWT/session) later.
        if not USER_ID_RE.match(x_user_id):
            raise HTTPException(400, "X-User-Id must be 8-64 characters of [A-Za-z0-9_-]")
        return x_user_id

    def catalog(request: Request) -> Catalog:
        return request.app.state.catalog

    def db(request: Request) -> Database:
        return request.app.state.db

    # ------------------------------------------------------------- helpers

    def user_state(cat: Catalog, store: Database, uid: str):
        stats = store.exercise_stats(uid)
        completed = {e for e, s in stats.items() if s["completed"]}
        statuses = cat.statuses(completed, set(stats))
        return stats, statuses

    def summarize(cat: Catalog, eid: str, stats: dict, statuses: dict) -> schemas.ExerciseSummary:
        s = stats.get(eid, {})
        return schemas.ExerciseSummary(
            **cat.exercises[eid].summary(), status=statuses[eid],
            attempts=s.get("attempts", 0), best_score=s.get("best_score"),
        )

    def ref(cat: Catalog, eid: str, statuses: dict) -> schemas.ExerciseRef:
        return schemas.ExerciseRef(id=eid, title=cat.exercises[eid].meta["title"], status=statuses[eid])

    def get_exercise(cat: Catalog, eid: str):
        if eid not in cat.exercises:
            raise HTTPException(404, f"Unknown exercise {eid!r}")
        return cat.exercises[eid]

    def to_submission(row: dict, include_code: bool, include_result: bool) -> schemas.Submission:
        return schemas.Submission(
            id=row["id"], exercise_id=row["exercise_id"], created_at=row["created_at"],
            status=row["status"], passed_tests=row["passed_tests"], total_tests=row["total_tests"],
            score=row["score"], duration_ms=row["duration_ms"],
            code=row["code"] if include_code else None,
            result=json.loads(row["result_json"]) if include_result else None,
        )

    # ------------------------------------------------------------- routes

    @app.get("/api/health")
    def health():
        return {"status": "ok"}

    @app.get("/api/curriculum", response_model=schemas.Curriculum)
    def get_curriculum(uid: str = Depends(user_id), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        stats, statuses = user_state(cat, store, uid)
        phases = []
        for phase in cat.curriculum["phases"]:
            modules = [
                schemas.Module(
                    id=m["id"], title=m["title"], concepts=m["concepts"],
                    exercise=summarize(cat, m["exercise"], stats, statuses) if m["exercise"] else None,
                )
                for m in phase["modules"]
            ]
            phases.append(schemas.Phase(id=phase["id"], title=phase["title"],
                                        description=phase["description"], modules=modules))
        return schemas.Curriculum(phases=phases)

    @app.get("/api/exercises/{exercise_id}", response_model=schemas.ExerciseDetail)
    def get_exercise_detail(exercise_id: str, uid: str = Depends(user_id),
                            cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        ex = get_exercise(cat, exercise_id)
        stats, statuses = user_state(cat, store, uid)
        return schemas.ExerciseDetail(
            **summarize(cat, ex.id, stats, statuses).model_dump(),
            task_markdown=ex.task_markdown,
            starter_code=ex.starter_code,
            prerequisite_details=[ref(cat, p, statuses) for p in ex.prerequisites],
            unlocks=[ref(cat, u, statuses) for u in cat.unlocks(ex.id)],
            time_limit_seconds=ex.meta.get("limits", {}).get("wall_seconds", 15),
        )

    @app.get("/api/exercises/{exercise_id}/submissions", response_model=list[schemas.Submission])
    def list_submissions(exercise_id: str, limit: int = 20, uid: str = Depends(user_id),
                         cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        get_exercise(cat, exercise_id)
        rows = store.list_submissions(uid, exercise_id, limit=min(max(limit, 1), 100))
        return [to_submission(r, include_code=True, include_result=True) for r in rows]

    @app.post("/api/exercises/{exercise_id}/submissions", response_model=schemas.SubmissionOut, status_code=201)
    async def submit(exercise_id: str, body: schemas.SubmissionIn, request: Request,
                     uid: str = Depends(user_id), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        ex = get_exercise(cat, exercise_id)
        _, before = user_state(cat, store, uid)
        if before[ex.id] == "locked":
            missing = [p for p in ex.prerequisites if before[p] != "completed"]
            raise HTTPException(403, f"Complete {', '.join(missing)} first")

        running = request.app.state.running_users
        if uid in running:
            raise HTTPException(429, "A run is already in progress for this user")
        running.add(uid)
        try:
            async with request.app.state.run_slots:
                result = await run_in_threadpool(grade, body.code, ex.dir)
        finally:
            running.discard(uid)

        row = store.add_submission(uid, ex.id, body.code, result)
        _, after = user_state(cat, store, uid)
        unlocked = [ref(cat, e, after) for e in cat.exercises if before[e] == "locked" and after[e] != "locked"]
        return schemas.SubmissionOut(
            **to_submission(row, include_code=False, include_result=True).model_dump(),
            newly_completed=before[ex.id] != "completed" and after[ex.id] == "completed",
            unlocked=unlocked,
        )

    @app.get("/api/progress", response_model=schemas.Progress)
    def get_progress(uid: str = Depends(user_id), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        stats, statuses = user_state(cat, store, uid)
        counts = {s: sum(v == s for v in statuses.values()) for s in ("completed", "in_progress", "available")}
        total_subs = sum(s["attempts"] for s in stats.values())
        recent = store.list_submissions(uid, limit=10)
        passes = sum(s["passes"] for s in stats.values())
        next_up = next((e for e in cat.order if statuses[e] == "in_progress"), None) \
            or next((e for e in cat.order if statuses[e] == "available"), None)
        return schemas.Progress(
            total_exercises=len(cat.exercises),
            **counts,
            total_submissions=total_subs,
            pass_rate=round(passes / total_subs, 4) if total_subs else 0.0,
            exercises=[
                schemas.ExerciseProgress(
                    exercise=summarize(cat, e, stats, statuses),
                    completed_at=stats.get(e, {}).get("completed_at"),
                    last_attempt_at=stats.get(e, {}).get("last_attempt_at"),
                )
                for e in cat.order
            ],
            recent=[to_submission(r, include_code=False, include_result=False) for r in recent],
            activity=store.activity(uid),
            next_up=summarize(cat, next_up, stats, statuses) if next_up else None,
        )

    return app


app = create_app()
