"""FastAPI control plane: courses, lessons, exercises, submissions, progress,
leaderboard and plans.

Run locally:  uvicorn api.main:app --reload
"""
import asyncio
import json
import re
from contextlib import asynccontextmanager
from dataclasses import dataclass

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request
from fastapi.concurrency import run_in_threadpool
from fastapi.middleware.cors import CORSMiddleware

from grader.run import grade

from . import schemas
from .catalog import Catalog, Step
from .config import Settings
from .db import Database
from .leaderboard import standings
from .names import clean_name, default_name
from .progression import Progression, evaluate

USER_ID_RE = re.compile(r"^[A-Za-z0-9_-]{8,64}$")


@dataclass
class Learner:
    """Everything about one learner needed to answer a request."""
    id: str
    user: dict
    stats: dict[str, dict]  # per-exercise submission stats
    lessons: dict[str, str]  # lesson_id -> completed_at
    progression: Progression

    @property
    def completed_exercises(self) -> set[str]:
        return {e for e, s in self.stats.items() if s["completed"]}


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or Settings()

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        app.state.catalog = Catalog(settings.exercises_dir, settings.lessons_dir)
        app.state.db = Database(settings.database_path)
        app.state.run_slots = asyncio.Semaphore(settings.max_concurrent_runs)
        app.state.running_users = set()
        yield

    app = FastAPI(title="Gradient: ML Practice Platform API", version="0.3.0", lifespan=lifespan)
    app.add_middleware(
        CORSMiddleware, allow_origins=settings.cors_origins, allow_methods=["*"], allow_headers=["*"],
    )

    # ------------------------------------------------------------- deps

    def catalog(request: Request) -> Catalog:
        return request.app.state.catalog

    def db(request: Request) -> Database:
        return request.app.state.db

    def user_id(x_user_id: str = Header(...)) -> str:
        # Anonymous learner identity generated by the client. Swap for real auth (JWT/session) later.
        if not USER_ID_RE.match(x_user_id):
            raise HTTPException(400, "X-User-Id must be 8-64 characters of [A-Za-z0-9_-]")
        return x_user_id

    def load_learner(cat: Catalog, store: Database, uid: str) -> Learner:
        user = store.ensure_user(uid, default_name(uid))
        stats = store.exercise_stats(uid)
        lessons = store.completed_lessons(uid)
        prog = evaluate(
            cat, user["plan"], set(lessons),
            {e for e, s in stats.items() if s["completed"]}, set(stats),
        )
        return Learner(uid, user, stats, lessons, prog)

    def learner(uid: str = Depends(user_id), cat: Catalog = Depends(catalog), store: Database = Depends(db)) -> Learner:
        return load_learner(cat, store, uid)

    # ------------------------------------------------------------- helpers

    def lock_reason(lr) -> schemas.LockReason | None:
        return schemas.LockReason(**lr.as_dict()) if lr else None

    def step_ref(cat: Catalog, step: Step, prog: Progression) -> schemas.StepRef:
        return schemas.StepRef(kind=step.kind, id=step.id, title=cat.title(step),
                               status=prog.status(step), course_id=step.course_id)

    def step_summary(cat: Catalog, step: Step, lr: Learner) -> schemas.StepSummary:
        state = lr.progression.steps[step.key]
        extra = {}
        if step.kind == "exercise":
            s = lr.stats.get(step.id, {})
            extra = {"difficulty": cat.exercises[step.id].meta.get("difficulty", "beginner"),
                     "attempts": s.get("attempts", 0), "best_score": s.get("best_score")}
        return schemas.StepSummary(
            **step_ref(cat, step, lr.progression).model_dump(),
            xp=cat.xp(step), estimated_minutes=cat.minutes(step),
            lock_reason=lock_reason(state.lock_reason), **extra,
        )

    def course_ref(cat: Catalog, course_id: str) -> schemas.CourseRef:
        c = cat.course_by_id[course_id]
        return schemas.CourseRef(id=c["id"], title=c["title"], tier=c.get("tier", "free"))

    def course_out(cat: Catalog, course: dict, lr: Learner) -> schemas.Course:
        state = lr.progression.courses[course["id"]]
        steps = cat.steps_by_course[course["id"]]
        modules = []
        for m in course["modules"]:
            lesson = next((s for s in steps if s.module_id == m["id"] and s.kind == "lesson"), None)
            exercise = next((s for s in steps if s.module_id == m["id"] and s.kind == "exercise"), None)
            modules.append(schemas.ModuleSummary(
                id=m["id"], title=m["title"], concepts=m["concepts"], coming_soon=not (lesson or exercise),
                lesson=step_summary(cat, lesson, lr) if lesson else None,
                exercise=step_summary(cat, exercise, lr) if exercise else None,
            ))
        return schemas.Course(
            id=course["id"], title=course["title"], tagline=course["tagline"], description=course["description"],
            level=course["level"], tier=course.get("tier", "free"), position=cat.courses.index(course) + 1,
            status=state.status, lock_reason=lock_reason(state.lock_reason),
            completed_steps=state.completed_steps, total_steps=state.total_steps,
            estimated_minutes=sum(cat.minutes(s) for s in steps), total_xp=sum(cat.xp(s) for s in steps),
            modules=modules,
        )

    def get_step(cat: Catalog, kind: str, ref: str) -> Step:
        step = cat.step_by_key.get((kind, ref))
        if not step:
            raise HTTPException(404, f"Unknown {kind} {ref!r}")
        return step

    def is_paywalled(state) -> bool:
        # Plan-locked content is withheld entirely; sequence-locked content can be previewed.
        return state.status == "locked" and state.lock_reason is not None and state.lock_reason.kind == "plan"

    def require_unlocked(lr: Learner, step: Step):
        state = lr.progression.steps[step.key]
        if state.status == "locked":
            raise HTTPException(403, state.lock_reason.message if state.lock_reason else "Locked")

    def newly_unlocked(cat: Catalog, before: Progression, after: Progression) -> list[schemas.StepRef]:
        return [step_ref(cat, s, after) for s in cat.steps
                if before.status(s) == "locked" and after.status(s) != "locked"]

    def xp_rank(cat: Catalog, store: Database, uid: str) -> tuple[int, int | None]:
        rows = standings(cat, store.xp_events())
        me = next((r for r in rows if r["user_id"] == uid), None)
        return (me["xp"], me["rank"]) if me else (0, None)

    def to_submission(row: dict, include_code: bool, include_result: bool) -> schemas.Submission:
        return schemas.Submission(
            id=row["id"], exercise_id=row["exercise_id"], created_at=row["created_at"],
            status=row["status"], passed_tests=row["passed_tests"], total_tests=row["total_tests"],
            score=row["score"], duration_ms=row["duration_ms"],
            code=row["code"] if include_code else None,
            result=json.loads(row["result_json"]) if include_result else None,
        )

    def next_up(cat: Catalog, prog: Progression) -> Step | None:
        return next((s for s in cat.steps if prog.status(s) == "in_progress"), None) \
            or next((s for s in cat.steps if prog.status(s) == "available"), None)

    # ------------------------------------------------------------- learner

    @app.get("/api/health")
    def health():
        return {"status": "ok"}

    def me_out(cat: Catalog, store: Database, lr: Learner) -> schemas.Me:
        xp, rank = xp_rank(cat, store, lr.id)
        return schemas.Me(
            display_name=lr.user["display_name"], plan=lr.user["plan"], xp=xp, rank=rank,
            exercises_completed=len(lr.completed_exercises), lessons_completed=len(lr.lessons),
            billing_mode=settings.billing_mode,
        )

    @app.get("/api/me", response_model=schemas.Me)
    def get_me(lr: Learner = Depends(learner), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        return me_out(cat, store, lr)

    @app.patch("/api/me", response_model=schemas.Me)
    def update_me(body: schemas.MeUpdate, lr: Learner = Depends(learner),
                  cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        name = clean_name(body.display_name)
        if not name:
            raise HTTPException(422, "Use 2–24 letters, numbers, spaces, dots, dashes or underscores")
        lr.user = store.update_user(lr.id, display_name=name)
        return me_out(cat, store, lr)

    @app.post("/api/billing/checkout", response_model=schemas.Me)
    def checkout(body: schemas.CheckoutIn, lr: Learner = Depends(learner),
                 cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        if settings.billing_mode != "demo":
            raise HTTPException(501, "Payments are not configured on this server")
        # Demo mode: no payment is taken. Replace with a payment-provider checkout session + webhook.
        lr.user = store.update_user(lr.id, plan=body.plan)
        return me_out(cat, store, lr)

    @app.post("/api/billing/cancel", response_model=schemas.Me)
    def cancel(lr: Learner = Depends(learner), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        if settings.billing_mode != "demo":
            raise HTTPException(501, "Payments are not configured on this server")
        lr.user = store.update_user(lr.id, plan="free")
        return me_out(cat, store, lr)

    # ------------------------------------------------------------- courses & lessons

    @app.get("/api/courses", response_model=list[schemas.Course])
    def list_courses(lr: Learner = Depends(learner), cat: Catalog = Depends(catalog)):
        return [course_out(cat, c, lr) for c in cat.courses]

    @app.get("/api/courses/{course_id}", response_model=schemas.Course)
    def get_course(course_id: str, lr: Learner = Depends(learner), cat: Catalog = Depends(catalog)):
        if course_id not in cat.course_by_id:
            raise HTTPException(404, f"Unknown course {course_id!r}")
        return course_out(cat, cat.course_by_id[course_id], lr)

    @app.get("/api/lessons/{lesson_id}", response_model=schemas.LessonDetail)
    def get_lesson(lesson_id: str, lr: Learner = Depends(learner), cat: Catalog = Depends(catalog)):
        step = get_step(cat, "lesson", lesson_id)
        lesson = cat.lessons[lesson_id]
        state = lr.progression.steps[step.key]
        nxt = cat.next_step(step)
        paywalled = is_paywalled(state)
        return schemas.LessonDetail(
            id=lesson.id, title=lesson.title, markdown="" if paywalled else lesson.markdown,
            estimated_minutes=lesson.estimated_minutes, xp=lesson.xp,
            status=state.status, lock_reason=lock_reason(state.lock_reason),
            completed_at=lr.lessons.get(lesson_id), course=course_ref(cat, step.course_id),
            module_title=step.module_title, questions=[] if paywalled else lesson.public_questions(),
            next=step_ref(cat, nxt, lr.progression) if nxt else None,
        )

    @app.post("/api/lessons/{lesson_id}/attempts", response_model=schemas.QuizAttemptOut)
    def attempt_quiz(lesson_id: str, body: schemas.QuizAttemptIn, lr: Learner = Depends(learner),
                     cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        step = get_step(cat, "lesson", lesson_id)
        require_unlocked(lr, step)
        lesson = cat.lessons[lesson_id]
        missing = [q["id"] for q in lesson.questions if q["id"] not in body.answers]
        if missing:
            raise HTTPException(422, f"Answer every question (missing: {', '.join(missing)})")
        results = lesson.grade(body.answers)
        passed = all(r["correct"] for r in results)
        newly = passed and store.complete_lesson(lr.id, lesson_id)
        after = load_learner(cat, store, lr.id).progression if newly else lr.progression
        return schemas.QuizAttemptOut(
            passed=passed, results=results, newly_completed=newly, xp_earned=lesson.xp if newly else 0,
            unlocked=newly_unlocked(cat, lr.progression, after) if newly else [],
        )

    # ------------------------------------------------------------- exercises

    @app.get("/api/exercises/{exercise_id}", response_model=schemas.ExerciseDetail)
    def get_exercise(exercise_id: str, lr: Learner = Depends(learner), cat: Catalog = Depends(catalog)):
        step = get_step(cat, "exercise", exercise_id)
        ex = cat.exercises[exercise_id]
        state = lr.progression.steps[step.key]
        s = lr.stats.get(exercise_id, {})
        lesson = next((m for m in cat.module_steps(step) if m.kind == "lesson"), None)
        nxt = cat.next_step(step)
        return schemas.ExerciseDetail(
            id=ex.id, title=ex.title, summary=ex.meta.get("summary", ""),
            difficulty=ex.meta.get("difficulty", "beginner"), estimated_minutes=ex.meta.get("estimated_minutes", 20),
            tags=ex.meta.get("tags", []), xp=ex.xp, status=state.status, lock_reason=lock_reason(state.lock_reason),
            attempts=s.get("attempts", 0), best_score=s.get("best_score"),
            course=course_ref(cat, step.course_id), module_title=step.module_title,
            lesson=step_ref(cat, lesson, lr.progression) if lesson else None,
            next=step_ref(cat, nxt, lr.progression) if nxt else None,
            task_markdown="" if is_paywalled(state) else ex.task_markdown,
            starter_code="" if is_paywalled(state) else ex.starter_code,
            time_limit_seconds=ex.meta.get("limits", {}).get("wall_seconds", 15),
        )

    @app.get("/api/exercises/{exercise_id}/submissions", response_model=list[schemas.Submission])
    def list_submissions(exercise_id: str, limit: int = 20, uid: str = Depends(user_id),
                         cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        get_step(cat, "exercise", exercise_id)
        rows = store.list_submissions(uid, exercise_id, limit=min(max(limit, 1), 100))
        return [to_submission(r, include_code=True, include_result=True) for r in rows]

    @app.post("/api/exercises/{exercise_id}/submissions", response_model=schemas.SubmissionOut, status_code=201)
    async def submit(exercise_id: str, body: schemas.SubmissionIn, request: Request,
                     lr: Learner = Depends(learner), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        step = get_step(cat, "exercise", exercise_id)
        require_unlocked(lr, step)

        running = request.app.state.running_users
        if lr.id in running:
            raise HTTPException(429, "A run is already in progress for this user")
        running.add(lr.id)
        try:
            async with request.app.state.run_slots:
                result = await run_in_threadpool(grade, body.code, cat.exercises[exercise_id].dir)
        finally:
            running.discard(lr.id)

        row = store.add_submission(lr.id, exercise_id, body.code, result)
        after = load_learner(cat, store, lr.id).progression
        newly = lr.progression.status(step) != "completed" and after.status(step) == "completed"
        return schemas.SubmissionOut(
            **to_submission(row, include_code=False, include_result=True).model_dump(),
            newly_completed=newly, xp_earned=cat.exercises[exercise_id].xp if newly else 0,
            unlocked=newly_unlocked(cat, lr.progression, after),
        )

    # ------------------------------------------------------------- progress & leaderboard

    @app.get("/api/progress", response_model=schemas.Progress)
    def get_progress(lr: Learner = Depends(learner), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        xp, rank = xp_rank(cat, store, lr.id)
        total_subs = sum(s["attempts"] for s in lr.stats.values())
        passes = sum(s["passes"] for s in lr.stats.values())
        ex_steps = [s for s in cat.steps if s.kind == "exercise"]
        nxt = next_up(cat, lr.progression)
        return schemas.Progress(
            xp=xp, rank=rank,
            total_exercises=len(ex_steps), exercises_completed=len(lr.completed_exercises),
            total_lessons=len(cat.lessons), lessons_completed=len(lr.lessons),
            total_submissions=total_subs, pass_rate=round(passes / total_subs, 4) if total_subs else 0.0,
            courses=[
                schemas.CourseProgress(id=c["id"], title=c["title"], status=lr.progression.courses[c["id"]].status,
                                       completed_steps=lr.progression.courses[c["id"]].completed_steps,
                                       total_steps=lr.progression.courses[c["id"]].total_steps)
                for c in cat.courses
            ],
            exercises=[
                schemas.ExerciseProgress(
                    exercise=step_summary(cat, s, lr), course_title=cat.course_by_id[s.course_id]["title"],
                    completed_at=lr.stats.get(s.id, {}).get("completed_at"),
                    last_attempt_at=lr.stats.get(s.id, {}).get("last_attempt_at"),
                )
                for s in ex_steps
            ],
            recent=[to_submission(r, include_code=False, include_result=False) for r in store.list_submissions(lr.id, limit=10)],
            activity=store.activity(lr.id),
            next_up=step_ref(cat, nxt, lr.progression) if nxt else None,
        )

    @app.get("/api/leaderboard", response_model=schemas.Leaderboard)
    def get_leaderboard(period: str = Query("all", pattern="^(all|week)$"), limit: int = Query(50, ge=1, le=100),
                        uid: str = Depends(user_id), cat: Catalog = Depends(catalog), store: Database = Depends(db)):
        store.ensure_user(uid, default_name(uid))
        rows = standings(cat, store.xp_events(), period)
        users = store.users_by_id([r["user_id"] for r in rows[:limit]] + [uid])

        def entry(r: dict) -> schemas.LeaderboardEntry:
            name = users.get(r["user_id"], {}).get("display_name") or default_name(r["user_id"])
            return schemas.LeaderboardEntry(
                rank=r["rank"], display_name=name, xp=r["xp"], exercises_completed=r["exercises"],
                lessons_completed=r["lessons"], is_me=r["user_id"] == uid,
            )

        me = next((r for r in rows if r["user_id"] == uid), None)
        return schemas.Leaderboard(
            period=period, total_learners=len(rows),
            entries=[entry(r) for r in rows[:limit]], me=entry(me) if me else None,
        )

    return app


app = create_app()
